# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
jobs:
  build-job:
    docker:
      # specify the version you desire here
        - image: circleci/node:latest
      
      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/mongo:3.4.4

    working_directory: ~/repo

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run: yarn install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
      - run:
          name: prettier
          command: yarn prettier-check
      - run:
          name: Run test
          command: yarn test --coverage --bail # make the test fail on the first failure
      - run:
          name: Upload coverage to codecov
          command: bash <(curl -s https://codecov.io/bash) -t $CODECOV_TOKEN

  deploy-job:
    machine: true
    steps:
      - checkout
      - run:
          name: build docker image for chat
          command: docker build -t hitochan777/chat:${CIRCLE_SHA1} .

      # - run:
      #     name: push docker image to docker hub
      #     command: docker push hitochan777/chat:${CIRCLE_SHA1}
      # - run:
      #     name: send command to the cloud service to pull image and run container
      #     command: docker run hitochan777/chat:${CIRCLE_SHA1} # TODO: replace when ready

workflows:
  version: 2
  build-deploy:
    jobs:
      - build-job
      - deploy-job:
          requires:
            - build-job
          filters:
            branches:
              only: master
