// @format
/*
 * This file contains all the action types.
 * No action types should be defined in other files by convention.
 *
*/
export const RECEIVE_USER = 'RECEIVE_USER'
export const REQUEST_FRIENDS = 'REQUEST_FRIENDS'
export const RECEIVE_FRIEND_IDS = 'RECEIVE_FRIEND_IDS'
export const REQUEST_ROOM_INFO = 'REQUEST_ROOM_INFO'
export const RECEIVE_ROOM_INFO = 'RECEIVE_ROOM_INFO'
export const RECEIVE_ROOM = 'RECEIVE_ROOM'
export const REQUEST_ROOMS = 'REQUEST_ROOMS'
export const REQUEST_ROOM = 'REQUEST_ROOM'
export const REQUEST_CREATE_ROOM = 'REQUEST_CREATE_ROOM'
export const RECEIVE_CREATE_ROOM = 'RECEIVE_CREATE_ROOM'
export const CHANGE_ROOM = 'CHANGE_ROOM'
export const REQUEST_DELETE_ROOM = 'REQUEST_DELETE_ROOM'
export const RECEIVE_DELETE_ROOM = 'RECEIVE_DELETE_ROOM'
export const REQUEST_MESSAGES = 'REQUEST_MESSAGES'
export const RECEIVE_MESSAGE = 'RECEIVE_MESSAGE'
export const USER_AUTH = 'USER_AUTH'
export const USER_LOGOUT = 'USER_LOGOUT'
export const OPEN_CREATE_GROUP_MODAL = 'OPEN_CREATE_GROUP_MODAL'
export const CLOSE_CREATE_GROUP_MODAL = 'CLOSE_CREATE_GROUP_MODAL'
export const SEND_CHAT_MESSAGE = 'SEND_CHAT_MESSAGE'
export const RECEIVE_MESSAGE_READ = 'RECEIVE_MESSAGE_READ'
export const SEND_MESSAGE_READ = 'SEND_MESSAGE_READ'
export const UNREAD_MESSAGES = 'UNREAD_MESSAGES'
